# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vVVQ08xhTj4Eq871_ueolvWspC1vgofV
"""

# 1. Ask for the Strike Price once
K = float(input("Enter the Strike Price (K): "))

print(f"\n--- Calculator for Strike {K} is ready ---")
print("Type 'exit' as the stock price to stop.\n")

while True:
    # 2. Get the current stock price scenario
    user_input = input("Enter the Stock Price at Expiry (S_T): ")

    # 3. Allow the user to quit
    if user_input.lower() == 'exit':
        print("Exiting calculator...")
        break

    # 4. Calculate Payoffs
    ST = float(user_input)
    call_payoff = max(ST - K, 0)
    put_payoff = max(K - ST, 0)

    # 5. Display Results with Exercise Logic
    print(f" > Call Option Payoff: {call_payoff}")
    if call_payoff > 0:
        print("   Result: Exercise it!")
    else:
        print("   Result: Will not exercise it.")

    print(f" > Put Option Payoff:  {put_payoff}")
    if put_payoff > 0:
        print("   Result: Exercise it!")
    else:
        print("   Result: Will not exercise it.")

    print("-" * 30)